# -*- coding: utf-8 -*-
"""vocodeurs_M1_TAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AeSUh5_QpNpoNbIQjaDFvsuloXNclA04
"""

!pip install librosa

!pip install IPython

!pip install pyworld

import librosa
import matplotlib.pyplot as plt
import numpy as np

#!pip install IPython
import IPython.display as ipd
from IPython.display import Audio

import pyworld as pw

signal, sr = librosa.load("PTSVOX_LG007_F_session1_mic_S_1_extrait1.wav", sr=None)

# 1. Signal temporel
plt.figure()
t = np.arange(len(signal))/sr
plt.plot(t,signal)
plt.title("Signal temporel")
plt.xlabel("temps (s)")
plt.ylabel("Amplitude")
plt.show()

# 2. FFT
from numpy.fft import fft, fftfreq
fft = fft(signal)
#fft = np.fft.fft(signal)
freqs = np.fft.fftfreq(len(signal), 1/sr)

plt.figure()
plt.plot(freqs, np.abs(fft))
plt.title("Spectre (FFT)")
plt.xlabel("Fréquence (Hz)")
plt.ylabel("Amplitude")
plt.xlim(0, 5000)
plt.show()

# 3. Spectrogramme
S = librosa.stft(signal)
S_db = librosa.amplitude_to_db(np.abs(S), ref=np.max)
#20 * log10(amplitude / ref)

plt.figure()
librosa.display.specshow(S_db, sr=sr, x_axis='time', y_axis='hz')
#plt.imshow(S_db, aspect='auto', origin='lower',extent= [0, len(signal)/sr, 0, sr/2])


plt.colorbar()
plt.ylim(0,5000)
plt.title("Spectrogramme")
plt.show()

"""Où se situe l’énergie principale ?

Peut-on identifier les zones voisées ?

Où apparaissent les harmoniques ?

"""

f0, voiced_flag, voiced_probs = librosa.pyin(
    signal,
    fmin=75,
    fmax=300,
    sr=sr
)

plt.figure()
plt.plot(f0)
plt.title("Estimation de F0")
plt.ylabel("Fréquence fondamentale (Hz)")
plt.ylim(75, 300)
plt.show()

"""Comparer F0 avec l’espacement des harmoniques dans le spectre.

Vérifier que l’écart entre pics ≈ F0.
"""

S = librosa.stft(signal)


times = librosa.times_like(f0, sr=sr)

S_db = librosa.amplitude_to_db(np.abs(S), ref=np.max)

plt.figure()
librosa.display.specshow(S_db, sr=sr, x_axis='time', y_axis='hz')
plt.plot(times, f0, color='cyan', linewidth=2)
plt.ylim(0, 5000)
plt.colorbar()
plt.title("Spectrogramme + F0")
plt.show()

# Enveloppe spectrale (idée source–filtre)
#print(signal.shape,10000/sr,12048/sr)

frame = signal[10000:12048]  # une trame
window = np.hamming(len(frame))
frame = frame * window

fft_frame = np.fft.rfft(frame)
freqs = np.fft.rfftfreq(len(frame), 1/sr)

plt.figure()
plt.plot(freqs, 20*np.log10(np.abs(fft_frame)))
plt.xlim(0, 5000)
plt.title("Spectre d'une trame")
plt.show()
#

# Étape 2 : Lissage = enveloppe spectrale ; Méthode simple : moyenne glissante




from scipy.ndimage import gaussian_filter1d

envelope = gaussian_filter1d(np.abs(fft_frame), sigma=10)

plt.figure()
plt.plot(freqs, np.abs(fft_frame), alpha=0.4)
plt.plot(freqs, envelope, linewidth=2)
plt.xlim(0, 5000)
plt.title("Structure harmonique + enveloppe")
plt.show()

t = np.arange(0, 0.03, 1/sr)
f0_mean = np.nanmean(f0)

excitation = np.sin(2*np.pi*f0_mean*t)
plt.plot(excitation)
plt.title("Excitation sinusoïdale")
plt.show()

!pip install pyworld



signal = signal.astype(np.float64)

#calcul f0
_f0, t = pw.dio(signal, sr)
f0 = pw.stonemask(signal, _f0, t, sr)
#filtre
sp = pw.cheaptrick(signal, f0, t, sr)
#apériodicité
ap = pw.d4c(signal, f0, t, sr)

# analyse - synthèse
y = pw.synthesize(f0, sp, ap, sr)

Audio(y, rate=sr)

Audio(signal, rate=sr)

# s'enregistrer avec praat, menu New, Record sound)

f0_plat = f0.copy()
voiced = f0 > 0
#f0_plat[voiced] = np.mean(f0[voiced])
f0_plat[voiced] = 100
print(np.mean(f0[voiced]))
y = pw.synthesize(f0_plat, sp, ap, sr)
Audio(y, rate=sr)

f0_haut = f0 * 1.3
#f0_haut = f0 * 0.8
y = pw.synthesize(f0_haut, sp, ap, sr)
Audio(y, rate=sr)

sp_mod = sp.copy()
sp_mod[:,200:] *= 0.8
print(sp_mod.shape)
y_mod = pw.synthesize(f0, sp_mod, ap, sr)

Audio(y_mod, rate=sr)

f0_stretch = np.repeat(f0, 2)
sp_stretch = np.repeat(sp, 2, axis=0)
ap_stretch = np.repeat(ap, 2, axis=0)

y = pw.synthesize(f0_stretch, sp_stretch, ap_stretch, sr)

Audio(y, rate=sr)

f0_zero = np.zeros_like(f0)
ap_whisper = np.ones_like(ap)

y = pw.synthesize(f0_zero, sp, ap_whisper, sr)

Audio(y, rate=sr)

import numpy as np
import pyworld as pw

# f0 originale
f0_mod = f0.copy()

# Remplacer les valeurs voisées uniquement
voiced = f0 > 0

# Créer une rampe linéaire
f0_min = 100
f0_max = 200

#np.linspace(100, 200, 5)
# Sortie : [100. 125. 150. 175. 200.]
f0_mod[voiced] = np.linspace(f0_min, f0_max, np.sum(voiced))

# Resynthèse
y_rise = pw.synthesize(f0_mod, sp, ap, sr)


Audio(y_rise, rate=sr)

"""# premier essai synthèse TTS avec WORLD

"""

!pip install pyworld
!pip install praat-textgrids

import numpy as np
import pyworld as pw
import textgrids
import soundfile as sf

!pip install IPython
import IPython.display as ipd
from IPython.display import Audio

NOM = 'PTSVOX_LG008_H_session2_mic_L_1_extraits'
signal, sr = sf.read(NOM + '.wav')
signal = signal.astype(np.float64)
PAS = 0.005

_f0, t = pw.dio(signal, sr)
f0 = pw.stonemask(signal, _f0, t, sr)
sp = pw.cheaptrick(signal, f0, t, sr)
ap = pw.d4c(signal, f0, t, sr)

tg = textgrids.TextGrid(NOM + '.corr.textgrid')
tier = tg["phonemes_c"]

def extraire_carac_phoneme(tier,phoneme):
  for a in tier:
    if a.text == phoneme:
      fd= int(a.xmin / PAS)
      ff = int(a.xmax / PAS)
      return fd,ff

fd_ss, ff_ss = extraire_carac_phoneme(tier,'ss')
fd_aa, ff_aa = extraire_carac_phoneme(tier,'aa')

f0_total = np.concatenate([f0[fd_ss:ff_ss],f0[fd_aa:ff_aa]])
sp_total = np.concatenate([sp[fd_ss:ff_ss],sp[fd_aa:ff_aa]])
ap_total = np.concatenate([ap[fd_ss:ff_ss],ap[fd_aa:ff_aa]])

y = pw.synthesize(f0_total, sp_total, ap_total, sr)
#sf.write("synthese_sa.wav",y,sr)
Audio(y, rate=sr)

"""# 2ème exercice : création d'un dictionnaire avec les phonèmes (f0, ap, sp, durée) pour la synthèse"""

from collections import defaultdict

NOM = 'PTSVOX_LG007_F_session2_mic_L_1'
signal, sr = sf.read(NOM + '.wav')
signal = signal.astype(np.float64)
PAS = 0.005

_f0, t = pw.dio(signal, sr)
f0 = pw.stonemask(signal, _f0, t, sr)
sp = pw.cheaptrick(signal, f0, t, sr)
ap = pw.d4c(signal, f0, t, sr)

tg = textgrids.TextGrid(NOM + '.corr.textgrid')
tier = tg["phonemes_c"]

phonemes_corpus = {
    'aa', 'ai', 'an', 'au', 'bb', 'ch', 'dd', 'ei', 'eu', 'ff', 'gg', 'ii',
    'in', 'jj', 'kk', 'll', 'mm', 'nn', 'oo', 'oe', 'on', 'ou', 'pp', 'rr',
    'ss', 'tt', 'uu', 'vv', 'ww', 'xx', 'yy', 'zz', 'uy'
}

dico_sp, dico_ap, dico_f0, dico_duree = defaultdict(list),defaultdict(list),defaultdict(list),defaultdict(list)

for a in tier:
  phoneme = a.text
  if phoneme in phonemes_corpus:
  #if phoneme not in phonemes_corpus:
    #continue
    fd= int(a.xmin / 0.005)
    ff = int(a.xmax / PAS)

    for frame in sp[fd:ff]: dico_sp[phoneme].append(frame)
    for frame in ap[fd:ff]: dico_ap[phoneme].append(frame)
    dico_f0[phoneme].append(np.mean(f0[fd:ff]))
    dico_duree[phoneme].append(ff-fd)


    dico = {}
    for phoneme in phonemes_corpus:
      dico[phoneme] = {
          "sp": np.mean(dico_sp[phoneme], axis = 0),
          "ap": np.mean(dico_ap[phoneme], axis = 0),
          "f0": np.mean(dico_f0[phoneme]),
          "duree": np.mean(dico_duree[phoneme])
      }

      # synthese
def synthetiseur(sequence):
  f0_total, sp_total, ap_total = [], [], []
  for phoneme in sequence:
    #ou n = int(dico[phoneme]["duree"], juste au cas où phoneme trop court
    n = max(1,int(dico[phoneme]["duree"]))
    f0_total.extend([dico[phoneme]["f0"]]*n)
    sp_total.extend([dico[phoneme]["sp"]]*n)
    ap_total.extend([dico[phoneme]["ap"]]*n)

  return pw.synthesize(np.array(f0_total), np.array(sp_total), np.array(ap_total), sr)


y = synthetiseur(["ss", "oo", "ll", "ei", "jj"])
Audio(y, rate=sr)