# -*- coding: utf-8 -*-
"""Copie de Vocodeurs_M1_TAL_version_finale.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17LEH2QP6uDSLaJDvCGsyKFepCE7HkvCH

Morgane Bona-Pellissier (Master 1 pluriTAL)
"""

!pip install praat-parselmouth
!pip install pyworld
!pip install IPython
!pip install praat-textgrids
!pip install soundfile

"""importation des librairies"""

import numpy as np
import pyworld as pw
import textgrids
import soundfile as sf
import parselmouth
import matplotlib.pyplot as plt
import librosa
import librosa.display
from parselmouth.praat import call
import IPython.display as ipd
from IPython.display import Audio
from collections import defaultdict

"""# 1-script principal synthese WORLD"""

"""
Modèle phonème-to-speech — LG007, session2_mic_L
"""
import numpy as np
import pyworld as pw
import textgrids
import soundfile as sf
from collections import defaultdict
from pathlib import Path

SR    = 44100
PAS   = 0.005

# Dictionnaires globaux (agrégés sur tous les fichiers)
dico_sp, dico_ap, dico_f0, dico_dur = (
    defaultdict(list),
    defaultdict(list),
    defaultdict(list),
    defaultdict(list),
)

# Diphones (phones IPA): clé "p__q" -> liste d'exemplaires (matrices de frames)
dico_diph_sp = defaultdict(list)
dico_diph_ap = defaultdict(list)
dico_diph_f0 = defaultdict(list)

# Longueur d'un diphone en frames WORLD (PAS=5ms -> 16 frames ~ 80ms)
DIPHONE_LEN_FRAMES = 16
DIPHONE_HALF = DIPHONE_LEN_FRAMES // 2

# Chemins fichiers audio et TextGrid
wavs = sorted(Path("audio").glob("*.wav"))
for wav_path in wavs:
    NOM = wav_path.stem          # ex: "1-1"
    signal, _ = sf.read(str(wav_path))
    tg_path = wav_path.with_suffix(".TextGrid")
    if not tg_path.exists():
        print(f"[WARN] TextGrid manquant, fichier ignoré: {tg_path}")
        continue
    tier = textgrids.TextGrid(str(tg_path))["phones"]

    # ---- Analyse WORLD ----
    signal     = signal.astype(np.float64)
    f0, t      = pw.harvest(signal, SR)
    f0         = pw.stonemask(signal, f0, t, SR)
    sp         = pw.cheaptrick(signal, f0, t, SR)
    ap         = pw.d4c(signal, f0, t, SR)

    segments = []  # liste ordonnée de tuples (phone, fd, ff)
    for a in tier:
        p = a.text.strip()
        # MFA (Kaldi) utilise typiquement "sil" (silence) et "spn" (bruit/parole non analysable)
        if not p or p in {"sil", "spn"}:
            continue

        fd = int(a.xmin / PAS)
        ff = int(a.xmax / PAS)
        if ff <= fd:
            continue

        # Sécurise les slices vides (peut arriver à cause des arrondis temps→trames)
        sp_seg = sp[fd:ff]
        ap_seg = ap[fd:ff]
        f0_seg = f0[fd:ff]
        if sp_seg.shape[0] == 0:
            continue
        #sp[fd:ff] extrait les frames WORLD du phonème courant — c'est une matrice de
        # shape (n_frames, n_bins). La boucle ajoute chaque frame individuellement dans
        # la liste dico_sp[p]. À la fin on aura toutes les frames de toutes les occurrences
        # du phonème p dans la même liste.
        #Pour f0 en revanche, on ne stocke pas chaque frame mais une seule valeur par
        # occurrence : la moyenne de F0 sur le segment. C'est un choix de simplification.

        for frame in sp_seg: dico_sp[p].append(frame)
        for frame in ap_seg: dico_ap[p].append(frame)
        dico_f0[p].append(np.nanmean(f0_seg))
        dico_dur[p].append(a.xmax - a.xmin)

        segments.append((p, fd, ff))

    # ---- Diphones: fin(p) + début(q) ----
    if DIPHONE_HALF > 0:
        for (p, p_fd, p_ff), (q, q_fd, q_ff) in zip(segments, segments[1:]):
            left_start = p_ff - DIPHONE_HALF
            left_end = p_ff
            right_start = q_fd
            right_end = q_fd + DIPHONE_HALF

            if left_start < p_fd:
                continue
            if right_end > q_ff:
                continue
            if left_start < 0 or right_start < 0:
                continue
            if left_end > sp.shape[0] or right_end > sp.shape[0]:
                continue

            sp_left = sp[left_start:left_end]
            ap_left = ap[left_start:left_end]
            f0_left = f0[left_start:left_end]

            sp_right = sp[right_start:right_end]
            ap_right = ap[right_start:right_end]
            f0_right = f0[right_start:right_end]

            if sp_left.shape[0] != DIPHONE_HALF or sp_right.shape[0] != DIPHONE_HALF:
                continue

            key = f"{p}__{q}"
            dico_diph_sp[key].append(np.concatenate([sp_left, sp_right], axis=0))
            dico_diph_ap[key].append(np.concatenate([ap_left, ap_right], axis=0))
            f0_d = np.concatenate([f0_left, f0_right], axis=0)
            f0_d = np.where(np.isnan(f0_d) | (f0_d <= 0), 0.0, f0_d).astype(np.float64)
            dico_diph_f0[key].append(f0_d)


# Dictionnaire final (moyennes globales par phonème)
dico = {}
for p in dico_sp:
    dico[p] = {
      "sp_frames": np.array(dico_sp[p]),   # (Nframes, nb_bins)
      "ap_frames": np.array(dico_ap[p]),
      "f0": np.mean(dico_f0[p]),
      "dur": np.mean(dico_dur[p]),
    }

print("nb phones:", len(dico_sp))
print("phones:", sorted(list(dico_sp.keys()))[:30], "...")
print({p: len(dico_sp[p]) for p in sorted(dico_sp)[:20]})
print("nb diphones:", len(dico_diph_sp))

# ---- Synthèse ----
def synthetiser(sequence):
    f0_tot, sp_tot, ap_tot = [], [], []
    for p in sequence:
        dur = dico[p]["dur"]
        f0_val = dico[p]["f0"]

        #On calcule combien de frames correspond à la durée moyenne du phonème.
        #Par exemple si dur = 0.08s et PAS = 0.005s, alors n = 16 frames.
        #Le max(1, ...) garantit qu'on a au moins 1 frame.
        n = max(1, int(dur / PAS))

        #[dico[p]["f0"]] * n crée une liste de n fois la même valeur de F0
        # .extend() ajoute ces valeurs à la liste globale.
        #extend ajoute les éléments d’une liste un par un, alors que append ajoute
        #la liste entière comme un seul bloc.
        if f0_val > 0:
          f0_tot.extend([f0_val] * n)
        else:
          f0_tot.extend([0] * n)

        frames_sp = dico[p]["sp_frames"]
        frames_ap = dico[p]["ap_frames"]

        # prend un bloc contigu de n frames (ou boucle si trop court)
        if len(frames_sp) >= n:
            start = np.random.randint(0, len(frames_sp) - n + 1)
            sp_seg = frames_sp[start:start+n]
            ap_seg = frames_ap[start:start+n]
        else:
            reps = int(np.ceil(n / len(frames_sp)))
            sp_seg = np.tile(frames_sp, (reps, 1))[:n]
            ap_seg = np.tile(frames_ap, (reps, 1))[:n]
        sp_tot.extend(sp_seg)
        ap_tot.extend(ap_seg)

    # WORLD attend des arrays, pas des listes Python
    return pw.synthesize(np.array(f0_tot), np.array(sp_tot), np.array(ap_tot), SR)


# ---- Synthèse diphones ----
def synthetiser_diphones(sequence, seed=None, overlap=3):
    """
    Synthèse concaténative à base de diphones (phones IPA).
    - sequence: liste de phones IPA (ex: ["s","ə","l","y",...])
    - overlap: fondu en frames entre unités
    Backoff: si un diphone manque, on retombe sur le monophone `q`.
    """
    rng = np.random.default_rng(seed)

    if len(sequence) < 2:
        return synthetiser(sequence)

    # nb_bins WORLD (souvent 513)
    any_phone = next(iter(dico))
    nb_bins = int(np.asarray(dico[any_phone]["sp_frames"]).shape[1])

    f0_out = np.zeros((0,), dtype=np.float64)
    sp_out = np.zeros((0, nb_bins), dtype=np.float64)
    ap_out = np.zeros((0, nb_bins), dtype=np.float64)

    def _append_unit(f0_u, sp_u, ap_u):
        nonlocal f0_out, sp_out, ap_out
        f0_u = np.asarray(f0_u).astype(np.float64)
        sp_u = np.asarray(sp_u).astype(np.float64)
        ap_u = np.asarray(ap_u).astype(np.float64)

        if f0_out.shape[0] == 0:
            f0_out = f0_u
            sp_out = sp_u
            ap_out = ap_u
            return

        k = int(overlap)
        k = max(0, min(k, f0_out.shape[0], f0_u.shape[0]))
        if k == 0:
            f0_out = np.concatenate([f0_out, f0_u], axis=0)
            sp_out = np.concatenate([sp_out, sp_u], axis=0)
            ap_out = np.concatenate([ap_out, ap_u], axis=0)
            return

        w = np.linspace(0.0, 1.0, k, dtype=np.float64)
        w2 = w[:, None]

        f0_out[-k:] = (1 - w) * f0_out[-k:] + w * f0_u[:k]
        sp_out[-k:] = (1 - w2) * sp_out[-k:] + w2 * sp_u[:k]
        ap_out[-k:] = (1 - w2) * ap_out[-k:] + w2 * ap_u[:k]

        f0_out = np.concatenate([f0_out, f0_u[k:]], axis=0)
        sp_out = np.concatenate([sp_out, sp_u[k:]], axis=0)
        ap_out = np.concatenate([ap_out, ap_u[k:]], axis=0)

    for p, q in zip(sequence, sequence[1:]):
        key = f"{p}__{q}"
        if key in dico_diph_sp and len(dico_diph_sp[key]) > 0:
            j = int(rng.integers(0, len(dico_diph_sp[key])))
            _append_unit(dico_diph_f0[key][j], dico_diph_sp[key][j], dico_diph_ap[key][j])
        else:
            # Backoff monophone: prendre DIPHONE_LEN_FRAMES frames dans la banque de q
            if q not in dico:
                continue
            sp_frames = np.asarray(dico[q]["sp_frames"])
            ap_frames = np.asarray(dico[q]["ap_frames"])
            n = int(DIPHONE_LEN_FRAMES)
            n_avail = int(sp_frames.shape[0])
            if n_avail <= 0:
                continue
            if n_avail >= n:
                start = int(rng.integers(0, n_avail - n + 1))
                sp_u = sp_frames[start:start + n]
                ap_u = ap_frames[start:start + n]
            else:
                reps = int(np.ceil(n / n_avail))
                sp_u = np.tile(sp_frames, (reps, 1))[:n]
                ap_u = np.tile(ap_frames, (reps, 1))[:n]

            f0_val = float(dico[q]["f0"])
            if np.isnan(f0_val) or f0_val <= 0:
                f0_u = np.zeros(n, dtype=np.float64)
            else:
                f0_u = np.full(n, f0_val, dtype=np.float64)
            _append_unit(f0_u, sp_u, ap_u)

    return pw.synthesize(f0_out, sp_out, ap_out, SR)

"""# 2-phonétisation"""

from pathlib import Path

phrases = [
    "Celui qui croyait au ciel, celui qui n'y croyait pas.",
    "Tous deux adoraient la belle, prisonière des soldats.",
    "Lequel montait à l'échelle et lequel guettait en bas",
    "Quand les blés sont sous la grelle, fou qui fait le délicat.",
    "Fou qui songe à ses querelles au coeur du commun combat.",
    "L'alouette et l'hirondelle, la rose et le réséda.",
]

out_dir = Path("tts_praat_phrases")
out_dir.mkdir(exist_ok=True)

synth = call("Create SpeechSynthesizer", "French (France)", "Steph")

tier_idx = 4

resultats_par_phrase = []

for idx, texte in enumerate(phrases, start=1):
    grille_synthetisee, son_synthetise = call(synth, "To Sound", texte, "yes")

    # Sauvegarde Praat TTS
    sf.write(out_dir / f"tts_{idx:02d}.wav", son_synthetise.values[0], int(son_synthetise.sampling_frequency))

    # Extraction pitch + phones/durées
    pitch = son_synthetise.to_pitch(time_step=0.01, pitch_floor=75, pitch_ceiling=500)

    resultats = []
    labels_absents = set()

    nb_phonemes = call(grille_synthetisee, "Get number of intervals", tier_idx)

    for i in range(1, nb_phonemes + 1):
        label = call(grille_synthetisee, "Get label of interval", tier_idx, i)
        if label == "":
            continue

        xmin = call(grille_synthetisee, "Get start time of interval", tier_idx, i)
        xmax = call(grille_synthetisee, "Get end time of interval", tier_idx, i)
        dur = xmax - xmin

        milieu = (xmin + xmax) / 2
        f0_val = pitch.get_value_at_time(milieu)
        if f0_val is None:
            f0_val = 0

        if label not in dico:
            labels_absents.add(label)
            continue

        resultats.append({"phoneme": label, "duree": dur, "f0": f0_val})

    print(f"[{idx:02d}] labels gardés:", sorted({r["phoneme"] for r in resultats}))
    print(f"[{idx:02d}] labels absents de dico:", sorted(labels_absents))

    resultats_par_phrase.append(resultats)

# Si tu veux inspecter la dernière phrase uniquement :
print("Dernière phrase resultats:", resultats_par_phrase[-1])



"""##############################################
# Jonction entre les 2
"""

all_sequences = []
all_durees = []
all_f0s = []

for resultats in resultats_par_phrase:   # une liste de dicts
    sequence = []
    durees = []
    f0s = []
    for r in resultats:                  # un dict {"phoneme","duree","f0"}
        p = r["phoneme"]
        if p not in dico:
            continue
        sequence.append(p)
        durees.append(r["duree"])
        f0s.append(r["f0"])

    all_sequences.append(sequence)
    all_durees.append(durees)
    all_f0s.append(f0s)



"""# avec les transitions entre phonèmes"""

"""
Fonction
"""
def synthetiser(sequence, durees=None, f0s=None):
    f0_tot, sp_tot, ap_tot = [], [], []

    for i, p in enumerate(sequence):
        dur = (durees[i] if durees is not None else dico[p]["dur"])
        n = max(1, int(dur / PAS))

        f0_val = (f0s[i] if f0s is not None else dico[p]["f0"])
        if f0_val is None or np.isnan(f0_val) or f0_val <= 0:
            f0_tot.extend([0.0] * n)
        else:
            f0_tot.extend([float(f0_val)] * n)

        # Format attendu: banque de frames WORLD pour chaque phone IPA
        sp_frames = np.asarray(dico[p]["sp_frames"])
        ap_frames = np.asarray(dico[p]["ap_frames"])

        if sp_frames.ndim == 1:
            # Cas rare: on n'a qu'un vecteur -> on répète
            sp_tot.extend([sp_frames] * n)
            ap_tot.extend([ap_frames] * n)
        else:
            n_avail = sp_frames.shape[0]
            if n_avail <= 0:
                continue
            if n_avail >= n:
                start = np.random.randint(0, n_avail - n + 1)
                sp_seg = sp_frames[start:start + n]
                ap_seg = ap_frames[start:start + n]
            else:
                reps = int(np.ceil(n / n_avail))
                sp_seg = np.tile(sp_frames, (reps, 1))[:n]
                ap_seg = np.tile(ap_frames, (reps, 1))[:n]

            sp_tot.extend(sp_seg)
            ap_tot.extend(ap_seg)

    return pw.synthesize(
        np.array(f0_tot),
        np.array(sp_tot),
        np.array(ap_tot),
        SR
    )

# ---- Exemples ----
y = synthetiser(["ss", "oo", "ll", "ei", "jj"])
sf.write("synthese_soleil.wav", y, SR)

for idx, resultats in enumerate(resultats_par_phrase, start=1):
    sequence = [r["phoneme"] for r in resultats]
    durees   = [r["duree"]   for r in resultats]
    f0s      = [r["f0"]      for r in resultats]

    y = synthetiser(sequence, durees=durees, f0s=f0s)
    sf.write(f"synthese_{idx:02d}.wav", y, SR)

"""# Autres modifications de qualité vocale
a- nasalité

"""

import numpy as np
import pyworld as pw
import soundfile as sf
import IPython.display as ipd
import matplotlib.pyplot as plt


# ---------- chargement ----------
x, sr = sf.read("PTSVOX_LG008_H_session2_mic_L_1_extraits.wav")
x = x.astype(np.float64)

# ---------- analyse WORLD ----------
f0, t = pw.harvest(x, sr)
sp = pw.cheaptrick(x, f0, t, sr)
ap = pw.d4c(x, f0, t, sr)

# ---------- modification nasale ----------

sp_nasal = sp.copy()
ap_nasal = ap.copy()

# axe fréquentiel
freqs = np.linspace(0, sr / 2, sp.shape[1])

# anti-formant nasal (creux large)
centre = 1300
largeur = 400

masque = 1 - 0.6 * np.exp(-0.5 * ((freqs - centre) / largeur) ** 2)
plt.plot(freqs, masque, label="masque (creux)")

sp_nasal *= masque

# plus de bruit (souffle nasal)
ap_nasal = np.clip(ap_nasal * 1.5, 0, 1)

#for i in range(sp.shape[0]):
#    sp_smooth[i] = np.convolve(sp[i], np.ones(15)/15, mode="same")


# ---------- synthèse ----------
y_nasal = pw.synthesize(f0, sp_nasal, ap_nasal, sr)

# ---------- écoute ----------
ipd.display(ipd.Audio(x, rate=sr))
ipd.display(ipd.Audio(y_nasal, rate=sr))

"""b- diminution d'une zone (cf. nasalité)"""

centre = 1500
largeur = 1000
profondeur = 5.7

notch = 1 - profondeur * np.exp(-0.5 * ((freqs - centre)/largeur)**2)
sp_notch = sp * notch

y = pw.synthesize(f0, sp_notch, ap, sr)

ipd.display(ipd.Audio(y, rate=sr))

"""c- amplification d'une zone fréquentielle"""

centre = 3000
largeur = 500
gain = 5.8

#des filtres spectraux (masque et boost) basés sur une gaussienne centrée sur une fréquence donnée.

boost = 1 + (gain - 1) * np.exp(-0.5 * ((freqs - centre)/largeur)**2)
sp_boost = sp * boost

y = pw.synthesize(f0, sp_boost, ap, sr)

ipd.display(ipd.Audio(y, rate=sr))

"""
# Créer une “voix hybride”

Objectif : combiner source et filtre de deux locuteurs."""

import soundfile as sf

wav1 = "PTSVOX_LG008_H_session2_mic_L_1_extraits.wav"   # source pour F0 et AP
wav2 = "PTSVOX_LG007_F_session2_mic_L_1_extrait2.wav"   # source pour le filtre spectral
out_wav = "synthese_mixte.wav"

# ---------- chargement ----------
x1, sr1 = sf.read(wav1)
x2, sr2 = sf.read(wav2)

#assert sr1 == sr2, "Les deux fichiers doivent avoir le même sampling rate"
#sr = sr1

# mono si besoin
#if x1.ndim > 1:
#    x1 = x1.mean(axis=1)
#if x2.ndim > 1:
#    x2 = x2.mean(axis=1)

x1 = x1.astype(np.float64)
x2 = x2.astype(np.float64)

# ---------- analyse WORLD ----------
f0_1, t1 = pw.harvest(x1, sr)
sp_1 = pw.cheaptrick(x1, f0_1, t1, sr)
ap_1 = pw.d4c(x1, f0_1, t1, sr)

f0_2, t2 = pw.harvest(x2, sr)
sp_2 = pw.cheaptrick(x2, f0_2, t2, sr)
ap_2 = pw.d4c(x2, f0_2, t2, sr)

# ---------- alignement longueur ----------
n_frames = min(len(f0_2), len(sp_1), len(ap_1))

f0_loc2 = f0_2[:n_frames]
sp_loc1 = sp_1[:n_frames]
ap_loc1 = ap_1[:n_frames]

# ---------- synthèse ----------
y = pw.synthesize(f0_loc2, sp_loc1, ap_loc1, sr)

# ---------- écoute ----------
ipd.display(ipd.Audio(y, rate=sr))

#y = pw.synthesize(f0_loc1, sp_loc2, ap_loc1, sr)

"""# réhausser tout le spectre"""

# Cette fois on garde F0, mais on change l’enveloppe spectrale sp.
# Option simple et très parlante :
# On déplace les formants en comprimant l’axe fréquentiel.

sp_mod = sp.copy()
#sp_mod = sp * 2
#sp_mod[:, 200:] *= 0.5


# Compression spectrale (facteur < 1 = voix plus grave/tube plus long)

facteur = 3  # <1 = voix plus "grande", >1 = plus "petite"
# np.arange(0, 10, 2)
for i in range(sp.shape[0]):
    indices = np.arange(sp.shape[1])
    new_indices = indices * facteur
    #new_indices[new_indices >= sp.shape[1]-1] = sp.shape[1]-1
    sp_mod[i] = np.interp(indices, new_indices, sp[i])

y_filter = pw.synthesize(f0, sp_mod, ap, sr)
Audio(y_filter, rate=sr)